version: '3'

services:
  app:
    build:
      context: node
    container_name: app
    networks:
      - desafio-node-network
    environment:
      - HOST=db
      - USER=root
      - PASSWORD=root
      - DATABASE=nodedb
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0 --init-file /data/application/init.sql
    container_name: db
    restart: always
    tty: true
    volumes:
      - .var:/var/lib/mysql
      - ./mysql/init.sql:/data/application/init.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - desafio-node-network
    ports:
      - "3306:3306"

  nginx:
    build:
      context: nginx
    container_name: nginx
    networks:
      - desafio-node-network
    depends_on:
      - app
    ports:
      - "8080:80"

networks:
  desafio-node-network:
    driver: bridge