version: '3'

services:
  app:
    build:
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: npm start
    networks:
      - desafio-node-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - .mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - desafio-node-network
    ports:
      - "3306:3306"

  nginx:
    build:
      context: nginx
    container_name: nginx
    networks:
      - desafio-node-network
    depends_on:
      - app
      - db
    ports:
      - "8080:80"

networks:
  desafio-node-network:
    driver: bridge